apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: back
  name: back
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}
